"""
NETWATCH application configuration.
"""

from pathlib import Path

APP_NAME = "NETWATCH"
APP_VERSION = "0.7.0"
APP_ENVIRONMENT = "development"

APPLICATION_NAME = APP_NAME
APPLICATION_VERSION = APP_VERSION

PROJECT_ROOT = Path(__file__).resolve().parent
CONFIGURATION_FILE = PROJECT_ROOT / "data" / "configuration.json"

AUTHORIZED_ASSESSMENT_ONLY = True

# Phase 3 - Port scanning
DEFAULT_SCAN_TIMEOUT = 1.0
DEFAULT_MAX_WORKERS = 20
MAX_SCAN_WORKERS = DEFAULT_MAX_WORKERS
DEFAULT_SUBMISSION_DELAY = 0.02
MAX_PORTS_PER_SCAN = 4096

# Phase 4 - DNS
DEFAULT_DNS_TIMEOUT = 3.0
DEFAULT_DNS_LIFETIME = 5.0

# Phase 5 - HTTP/HTTPS
DEFAULT_HTTP_TIMEOUT = 5.0
DEFAULT_MAX_REDIRECTS = 5

# Phase 6 - Traffic analysis
DEFAULT_TRAFFIC_CAPTURE_DURATION = 10.0
DEFAULT_TRAFFIC_PACKET_COUNT = 1000
MAX_TRAFFIC_CAPTURE_DURATION = 300
MAX_TRAFFIC_PACKET_COUNT = 100000

# Phase 8 - Firewall analysis
DEFAULT_FIREWALL_BROAD_PORT_THRESHOLD = 1000